### ISSUE TITLE
Todo Issue

### ISSUE THREAD

**Issue by marcello3d** [marcello3d/collabodux#7]
- [ ] Make json-diff3 more generic/improve authoring of three-way-merge functions
  - Right now json-diff3 takes over until there’s a conflict, but it removes a lot of control
  - What if json-diff3 was a collection of functions that could be composed to make a merger
  - Things to think about:
    - [ ] Allow treating `[number,number]` as an atomic unit that should be merged
    - [ ] Allow ImmutableJS types in tree
    - [ ] Allow more complex CRDT types in tree
  - Should the normalize/validate function be at a per-field level rather than global to the entire document? Should it be part of the merge function?
- [ ] Local persistence: helps with bad connections and offline mode
- [ ] Connection UX: indicate to user when they’re working offline
- [ ] Conflict UX: what is the flow to actually ask the user about a conflict before resolving it?
